language: node_js

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - "npm install"

after_success:
  - coveralls
