language: node_js

node_js:
  - "node"
  - "6"
  - "8"
  - "10"
  - "12"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - npm install
  - npm install codacy-coverage coveralls istanbul remap-istanbul -g

script:
  - npm test

after_success:
  - "npm run coverage"
  - "remap-istanbul --type lcovonly -i coverage/coverage.json -o coverage/remapped-lcov.info"
  - "cat coverage/remapped-lcov.info | codacy-coverage"
  - "cat coverage/remapped-lcov.info | coveralls"
